export {default as About} from './About/About'
export {default as Footer} from './Footer/Footer'
export {default as Header} from './Header/Header'
export {default as Project} from './Project/Project'
// export {default as Contact} from './Contact/Contact'
export {default as FormikContact} from './Contact/FormikContact'
export {default as Education} from './Education/Education'
export {default as Skills} from './Skills/Skills'